### ISSUE TITLE
Items Pending Database Updates

### ISSUE THREAD

**Issue by dcochs3** [MagiShi/CrunchApp#118]
- As a registered user, I want to add an item to folders so that I can organize props and costumes based on the production(s) they are used in.
- Edit Item to Folder Page

- [x] If an item already exists in a production folder, show that production folder as already highlighted **(depends on Amy/database updates)** **(Dana)**
- [x] Pressing the "add to selected production folders" button adds the item to that production folder (associated a tag) **(depends on Amy/database updates)**
- [x] A confirmation message appears on the item detail page that the item was successfully added to (selected production folders) **(depends on Amy/database updates)**
- [x] An error message appears if the item addition to that production folder failed **(depends on Amy/database updates)**
- [x] Deleting a production folder will remove that folder as a tag from associated items (depends on Amy/database updates)
