### ISSUE TITLE
As a registered user, I want to make a new reservation for an item to rent for use so that other users cannot rent out the same item.

### ISSUE THREAD

**Issue by dainryoo** [MagiShi/CrunchApp#18]
## Story/Task Details
- [x] Reservation button on "Item Detail" page takes user to "Set Reservation" page when pressed (#107)
- [x] "Set Reservation" page has form to input reservation details (#108)
- [x] "Set Reservation" page has a cancel and reserve button (#109)
- [x] When reservation is canceled, alert message asks if user is sure they want to proceed.  **(Phuc)** (#111)
- [x] Grey out the unavailable time in the calendar (#112)
- [x] When reservation is submitted, reservation information is saved to database (#99) **(Maggie)**
- [x] When reservation is submitted, there is a confirmation message  (#99) **(Maggie)**
- [x] When reservation is created, the user is taken to their reservations page (#113)
- [x] If an item is currently reserved, text appears above the "Reserve Item" button on the Item Detail page saying "Currently reserved until (end reservation date)." If the item is not currently reserved, no text appears. (#121)

## Acceptance Scenarios
_Scenario: The reservation has no time conflicts with another user’s reservations or time conflicts due to item repairs._
- Given the registered user is on the item detail page;
- When the registered user press the set reservation button
and enter in the dates they want to rent it out for;
- Then the registered user sees a success message that says the item has been reserved
    and they receive a confirmation email
and the application will store and display the reserved time period for the item;

## Done Done Criteria
