### ISSUE TITLE
As a registered user, I want to delete a reservation I previously made for an item so that the item can be freed to be reserved by other users.

### ISSUE THREAD

**Issue by dcochs3** [MagiShi/CrunchApp#20]
## Story/Task Details
**This will behave like Production Folders page**
- [x] Each reservation on a user's "Reservation Page" has an in-line "X" for deleting a reservation **(Da-In)** (#100)
- [x] Pressing the delete button prompts an alert ("Are you sure you want to delete this reservation?) **(Phuc)** (#111)
- [x] Pressing cancel removes alert and keeps user on "Reservation Page" **(Phuc)** (#111)
- [ ] Choosing the proceed with deletion removes that reservation from the "Reservation Page" **(Tommy)**
- [ ] The user stays on their now updated "Reservation Page." **(Tommy)**

## Acceptance Scenarios
_Scenario: The registered user wants to delete the reservation they made for an item._
- Given the registered user is on their reservations page;
- When the registered user presses the delete reservation button for the item they no longer want to reserve;
- Then the registered user sees a success message that says the reservation has been deleted
and they remain on their updated reservations page.

## Done Done Criteria
