### ISSUE TITLE
As a registered user, I want to set/change the time of a future reservation I had previously made for an item so that I can rent out my item during the time I actually need it.

### ISSUE THREAD

**Issue by dcochs3** [MagiShi/CrunchApp#21]
## Story/Task Details 
**Do we want the editing to be in-line or on to a new page?**
- [x] Each reservation on a user's "Reservation" page has an edit button (pencil icon) **(Da-In)** (note: use svg file) (#100)
- [x] Grey out the unavailable time in the calendar **(Phuc)** (#112)
- [x] The "Edit Reservation" page is pre-filled with the reservation's original information. (querying database) **(Maggie)** (#106)
- [x] Choosing to save the changes saves changes in database **(Maggie)**

## Acceptance Scenarios
_Scenario: The reservation has no time conflicts._
- Given the registered user presses an item’s edit reservation button;
- When the registered user enters a new time period for the reservation
and they press the save edits button;
- Then the registered user sees a success message that says the reservation has been changed
    and they remain on their updated reservations page.

_Scenario: The reservation has a time conflict with another user’s reservations._
- Given the registered user presses an item’s edit reservation button;
- When the registered user enters a new time period for the reservation
and they press the save edits button;
- Then the registered user sees a warning message that says there is a time conflict with another reservation
and they remain on their unchanged reservations page.

_Scenario: The reservation is longer than the application’s set maximum time limit._
- Given the registered user presses an item’s edit reservation button;
- When the registered user enters a new, lengthy time period for the reservation
and they press the save edits button;
- Then the registered user sees a warning message that says the selected time period is too long
and they remain on their unchanged reservations page.

_Scenario: The reservation is for an invalid time period._
- Given the registered user presses an item’s edit reservation button;
- When the registered user enters a new, invalid time period for the reservation
and they press the save edits button;
- Then the registered user sees a warning message that says the selected time period is invalid
and they remain on their unchanged reservations page.

## Done Done Criteria
