### ISSUE TITLE
Sprint 2 HTML/CSS clean up

### ISSUE THREAD

**Issue by dainryoo** [MagiShi/CrunchApp#25]
- [x] Try to get all CSS class names the same format
- [x] Are we doing bootstrap for sure? If so, make sure the hierarchy is container-fluid -> row -> col-x
- [x] Make HTML/CSS more understandable and structured
- [x] Make navbar consistent across all pages (separate navbar css page) **(Phuc)**
