### ISSUE TITLE
Sprint 2 Tidy-Up

### ISSUE THREAD

**Issue by dcochs3** [MagiShi/CrunchApp#29]
- [x] All items in database show up on the home page (backend)
- [x] Clicking on a single item's "details" link takes user to its item detail page
- [x] Add Item page has a color select option
- [x] Add Item page has a time period select option
- [x] Add Item page has a condition select option
- [x] Adding an item can support up to 3 photos
- [x] Item Detail page mirrors the new characteristics on the Add Item page
- [x] Edit Delete and Edit button coloration to be opaque
- [x] The main content is hidden underneath the navbar (in item page) when scaling down the width
- [x] Link the functionality to Add Item button on navbar in all of the pages. Only the one in home page works for now. And the thracker logo as well.
