### ISSUE TITLE
As a registered user, I want to view any reservations I have previously made for items so that I can keep track of my upcoming item reservations.

### ISSUE THREAD

**Issue by dainryoo** [MagiShi/CrunchApp#39]
## Story/Task Details
- [x] User's "Reservation Page" has a list of reservations (front-end) (#98)
- [x] User's "Reservation Page" shows a list of their associated reservations (pull from database) (#110)
- [x] Each reservation displays the begin date, the end date, the reserved item's name, and a link to the reserved item's detail page (front-end) **(Da-In)** (#100)
- [x] The link of the item's name directs to the item's detail page
- [x] Each reservation displays its actual information (pull from database) (#110)
- [x] There is an option to list the reservation by closest begin date, furthest begin date, closest end date, furthest end date, and alphabetically. **(Da-In)** (#101)
- [x] Filter for Past/Ongoing/Upcoming reservations. **(Da-In)** (#102)

## Acceptance Scenarios

_Scenario: The user has no ongoing or upcoming reservations._
- Given the user has no ongoing or upcoming reservations;
- When the user is on their reservations page;
- Then the user will not see any reservations listed.

_Scenario: The user has ongoing or upcoming reservations._
- Given the user has made reservations;
- When the user is on their reservations page;
- Then the user will see a list of their reservations in chronological order, with the closest reservation first.

## Done Done Criteria
