### ISSUE TITLE
As a user, I want to lookup an item by filtering characteristics so that I can examine its characteristics.

### ISSUE THREAD

**Issue by dcochs3** [MagiShi/CrunchApp#46]
## Story/Task Details
- [x] Filter menu should have radio buttons, sliders, etc. (turn it into a form?) **(Da-In)**
- [x] Section for filtered characteristics to be listed on the top of the homepage **(Da-In)**
- [x] Have the filtered characteristics show up on the homepage **(Da-In** will try)
- [x] Add "Go" or "Search" button to Filter menu **(Da-In)**
- [x] Queries to database upon clicking filter button **(Maggie)**
- [x] Have homepage's list of items update as the filter menu is updated (homepage should show the items matching the query) **(Tommy)**
- Stretch Goal: Dynamic queries to database

## Acceptance Scenarios

_Scenario: There are items that match the selected characteristics._
- Given the user is on the lookup item page;
- When the user chooses the characteristic(s) they would like to filter with;
- Then the user sees a list of all items that match any of the selected characteristics.

_Scenario: There are no items that match the selected characteristics._
- Given the user is on the lookup item page;
- When the user chooses the characteristic(s) they would like to filter with;
- Then the user sees a message that says there are no items that match the selected characteristics.

## Done Done Criteria
