### ISSUE TITLE
As a registered user, I want to add an item to folders so that I can organize props and costumes based on the production(s) they are used in.

### ISSUE THREAD

**Issue by dcochs3** [MagiShi/CrunchApp#47]
**Edit Item to Folder Page**
- [x] Item detail page has a button that says "Add to/Remove from Production Folder" (#60)
- [x] The "Add to/Remove from Production Folder" button on the item detail page directs to the Item to Folder page (#61)
- [x] Edit Item to Folder page has a form with a list of all production folders (front-end) (#62)
- [x] Page has specific item id/name ("Choose which folders you want to add/remove [itemName] from.") (#71)
- [x] Edit Item to Folder page has a form with a list of all production folders (back-end) (#82)
- [x] The Item to Folder page has a "Create new Production Folder" button (#63)
- [x] The "Create New Production Folder" button shows create pop up (#83)
- [x]  Create New Folder button: validate the input before passing in back-end. (#90) **(Phuc)**
- [x] Pressing "Create" on the pop up adds new folder to the database and refreshes the page and the new production folder appears in the list of all production folders  (#91) **(Maggie)**
- [x] The Item to Folder page allows multiple select (and deselect) (#64)
- [x] The production folder selection form has an "add to selected production folders" button and a "cancel" button (#65)
- [x] Pressing the "add to selected production folders" button navigates user back to item detail page
- [x] Pressing the "cancel" button shows an "are you sure you want to cancel" message (#66)
- [x] Pressing the "cancel" button directs the user back to the item detail page (#66)
- [x] Pressing the "stay on page" button directs the user back to editing production folders (#66)

## Acceptance Scenarios

_Scenario: The item does not already belong to the production folder._
- Given the user is on the item's detail page;
- When the user presses the "Add to Production Folder" button
and they select which production folder(s) they want to add the item to or they create a new production folder to add the item to;
- Then the user returns to the item detail page
and they see a confirmation message that says the item was added to the appropriate production folder.

_Scenario: The item already belongs to the production folder._
- Given the user is on the item's detail page;
- When the user presses the "Add to Production Folder" button;
- Then the user sees a list of production folders with the desired folder already highlighted.

## Done Done Criteria

**Comment by dcochs3** [comment]
How will we view the production folders?
How will we view the contents of the production folders?
Should be able to filter by which production an item is used in (if it belongs to that production folder).
