### ISSUE TITLE
Production Folder Creation and Management

### ISSUE THREAD

**Issue by MagiShi** [MagiShi/CrunchApp#69]
## Story/Task Details
**Production Folders Page**
- [x] The account nav bar has a link for production folders
- [x] The production folder link in the account nav bar directs to the Production Folders page (#55)
- [x] The Production Folders page shows a list of existing production folders (#78)
- [x] The Production Folders page has a "Create New Folder" button (#56)
- [x] Each Folder line has a delete button (like an "x") (#70)
- [x] Each Folder has an edit button (like a pencil icon to edit the name) (#70)
- [x] Edit button (pencil icon) opens pop-up with Cancel and Save (#77)
- [x] Editing pop-up has the pre-filled name field (#77)
- [x] Clicking Save in editing pop-up will add the new name of production folder into the database (#79)
- [x] The Production Folders page has a "Delete Folder" button (#56)
- [x] The delete folder button shows an "are you sure?" message
- [x] After confirming delete, the folder will be marked as "Pending Deletion" (requires admin approval) **(#92)** **(Maggie)**
- [x] The Production Folders page has a "View Contents" button (#56)
- [x] Clicking on a production folder directs to the Contents page (#84)
- [x] Create Production Folder Contents page (#84)
- [x] Create new Production Folder pop-up (#80)
- [x] Check the duplicate name when renaming or creating a folder. Also other validations. (#90) **(Phuc)**
- [x] Clicking 'Create' in pop-up add the new folder into database **(93)** **(Maggie)**
- [x] Creating a new Production folder refreshes the page, with the new info. **(93)** **(Maggie)**

Stretch Goal: Have a way to add (multiple) items to the folder from the folder contents page; Back button functionality

## Done/Done Criteria
